server:
  port: 8904

spring:
  h2:
    console:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
          brokers:
            - localhost:9092
      bindings:
        transaction-in-channel:
          destination: transaction-topic
          content-type: application/json
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  instance:
    prefer-ip-adress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/
