server:
  port: 8904

spring:
  h2:
    console:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
          brokers:
            - localhost:9092
      bindings:
        transaction-in-channel:
          destination: transaction-topic
          content-type: application/json
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5433/transaction-service
    username: masteruser
    password: password
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-adress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/
