version: '3.3'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    links:
      - zookeeper
    ports:
      - "9092:9092"
    hostname: localhost
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  user-service-db:
    image: postgres:12
    environment:
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-service
    ports:
      - 5432:5432

  order-service-db:
    image: postgres:12
    environment:
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order-service
    ports:
      - 5432:5432