server:
  port: 8903

spring:
  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
          brokers:
            - localhost:9092
      bindings:
        order-created-in-channel:
          destination: order-created-topic
          content-type: application/json
        order-created-out-channel:
          destination: order-created-topic
          content-type: application/json
        transaction-out-channel:
          destination: transaction-topic
          content-type: application/json
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: masteruser
    password: password
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-adress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/
