server:
  port: 8901

spring:
  application:
    name: auth-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'

eureka:
  instance:
    prefer-ip-adress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/


management:
  endpoints:
    routes:
      enabled: true
    web:
      exposure:
        include=*: